config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get 'contact', to: 'static_pages#contact'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' },
                     path_names: { sign_in: 'login',
                                   sign_out: 'logout',
                                   password: 'secret',
                                   sign_up: 'registration' }

  resources :courses, only: :show do
    resources :lessons, only: [:index, :show]
  end

  resources :lessons, only: [] do
    resources :answers, only: [:index, :create]
  end

  resource :profile, only: [:edit, :update]

  namespace :api do
  end

  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end

  namespace :admin do
    root to: 'main#index'

    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show
    resources :answers, only: [:index, :destroy]

    resources :user_lessons, only: :update do
      resources :answers, only: [:new, :create, :edit, :update]
    end

    resources :courses, except: :show do
      resources :lessons, except: :show
      resources :flows, except: :show
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end

      resources :lessons, only: [] do
        resources :tinymce_images, only: :create, owner: 'lesson'
      end

      resources :user_lessons, only: [] do
        resources :answers, only: :create
      end
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  include Authority::Abilities

  belongs_to :course
  belongs_to :section

  has_many :tinymce_images, as: :owner, dependent: :destroy

  has_many :user_lessons, dependent: :destroy
  has_many :users, through: :user_lessons

  scope :stop_lessons, -> { where(stop_lesson: true) }
  scope :free, -> { where(free: true) }

  validates :name, presence: true
  validates :section_id, presence: true

  mount_uploader :main_image, MainLessonImageUploader

  acts_as_list

  def previous
    return if position == 1

    course.lessons.find_by(position: position - 1)
  end

  def next
    course.lessons.find_by(position: position + 1)
  end
end

app/controllers/admin/api/lessons/mass_updates_controller.rb
class Admin::Api::Lessons::MassUpdatesController < Admin::Api::BaseController
  def create
    ::Lessons::MassUpdate.create!(lessons_params)

    head :no_content
  end

  private

  def lessons_params
    params.permit(lessons: [:id, :position, :section_id])[:lessons].values
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::BaseController
  before_action :set_course_and_breadcrumbs, except: :sort
  before_action :set_lesson, only: [:edit, :update, :destroy]

  def index
  end

  def new
    add_breadcrumb "Новое Занятие", [:new, :admin, @course, :lesson]

    @lesson = @course.lessons.build
  end

  def create
    @lesson = @course.lessons.build(lesson_params)

    if @lesson.save
      redirect_to after_save_path, notice: 'Занятие успешно создано'
    else
      add_breadcrumb "Новое Занятие", [:new, :admin, @course, :lesson]

      flash.now[:alert] = 'Не удалось создать Занятие'
      render :new
    end
  end

  def edit
    add_breadcrumb "Редактировать #{@lesson.name}", [:edit, :admin, @course, @lesson]
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to after_save_path, notice: 'Занятие успешно изменено'
    else
      add_breadcrumb "Редактировать #{@lesson.name}", [:edit, :admin, @course, @lesson]
      flash.now[:alert] = 'Не удалось изменить Занятие'
      render :edit
    end
  end

  def destroy
    if @lesson.destroy
      redirect_to [:admin, @course, :lessons], notice: 'Занятие успешно удалено'
    else
      redirect_to [:admin, @course, :lessons], alert: 'Не удалось удалить Занятие'
    end
  end

  private

  def set_course_and_breadcrumbs
    @course = Course.find(params[:course_id])

    add_breadcrumb 'Курсы', :admin_courses_path
    add_breadcrumb @course.name, [:admin, @course, :lessons]
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_active_main_menu_item
    @main_menu[:courses][:active] = true
  end

  def lesson_params
    params.require(:lesson).permit(:name, :description, :section_id, :main_image,
                                   :main_image_cache, :stop_lesson, :free, :video, :without_homework,
                                   :homework)
  end

  def after_save_path
    if params[:commit] == 'Сохранить и продолжить'
      [:edit, :admin, @course, @lesson]
    else
      [:admin, @course, :lessons]
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationBaseController
  before_action :authenticate_user!

  before_action :set_course, only: [:index, :show]
  before_action :set_breadcrumbs, only: [:index, :show]
  before_action :set_inner_flash_position, only: [:index, :show]

  def index
    authorize_action_for @course
    add_breadcrumb 'Программа занятий', '#'
  end

  def show
    @lesson = @course.lessons.find(params[:id])
    authorize_action_for @lesson

    @user_lesson = current_user.user_lessons.find_by(lesson: @lesson)
    @answer = current_user.answers.new(user_lesson: @user_lesson)
    # @answer.answer_images.build

    add_breadcrumb 'Программа занятий', [@course, :lessons]
    add_breadcrumb @lesson.name, '#'
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_breadcrumbs
    add_breadcrumb @course.name, @course
  end

  def set_inner_flash_position
    @flash_position = :inner
  end
end

app/views/admin/lessons/_form.html.slim
= simple_form_for [:admin, @course, @lesson], wrapper: :horizontal_form, html: { class: 'form-horizontal' } do |f|
  = f.input :name
  = f.association :section, collection: @course.sections.order(:position)
  = f.input :free, wrapper: :horizontal_radio_and_checkboxes
  = f.input :stop_lesson, wrapper: :horizontal_radio_and_checkboxes
  = f.input :main_image, wrapper: :horizontal_file_input
  = f.input :main_image_cache, as: :hidden
  = f.input :video

  - if @lesson.persisted?
    = f.input :description, input_html: { class: 'tinymce', rows: 40, cols: 120 }
    = tinymce(uploadimage_form_url: admin_api_lesson_tinymce_images_path(@lesson))

    = f.input :without_homework, wrapper: :horizontal_radio_and_checkboxes
    = f.input :homework, input_html: { class: 'tinymce', rows: 40, cols: 120 }
    = tinymce(uploadimage_form_url: admin_api_lesson_tinymce_images_path(@lesson))

  .row
    .col-md-11.col-md-offset-3.button_box
      = f.button :submit, 'Сохранить и продолжить', class: 'btn btn-primary'
      = f.button :submit,  'Сохранить', class: 'btn btn-primary'
      = link_to 'Отменить', [:admin, @course, :lessons], class: 'btn btn-default'
      = link_to 'Удалить', [:admin, @course, @lesson], class: 'btn btn-danger', method: :delete, data: { confirm: 'Действительно хотите удалить?' } if @lesson.persisted?

app/views/admin/lessons/_lesson.html.slim
tr.lesson data-id=lesson.id
  td
    span.handle.glyphicon.glyphicon-magnet
  td
    .btn-group-vertical role="group"
      = link_to [:edit, :admin, @course, lesson], class: 'btn btn-primary btn-sm' do
        span.glyphicon.glyphicon-pencil aria-hidden="true"
      = link_to [:admin, @course, lesson], class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Действительно хотите удалить?' } do
        span.glyphicon.glyphicon-trash aria-hidden="true"
  td.position= lesson.position
  td= lesson.name

app/views/admin/lessons/_section.html.slim
tr.section data-id=section.id
  td.text-center.success colspan=4
    h5= section.name

= render section.lessons.order(:position)

app/views/admin/lessons/edit.html.slim
h3 Редактирование Занятия
br

= render 'form'

app/views/admin/lessons/index.html.slim
h3 Занятие

= link_to 'Добавить занятие', [:new, :admin, @course, :lesson], class: 'btn btn-success pull-right'

table.table.table-striped
  thead
    tr
      th
      th
      th Номер
      th Название

  tbody.lessons_sortable data-update-url=admin_api_lessons_mass_update_path
    = render partial: 'section', collection: @course.sections.order(:position)

app/views/admin/lessons/new.html.slim
h3 Новое Занятие
hr

= render 'form'