config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get 'contact', to: 'static_pages#contact'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' },
                     path_names: { sign_in: 'login',
                                   sign_out: 'logout',
                                   password: 'secret',
                                   sign_up: 'registration' }

  resources :courses, only: :show do
    resources :lessons, only: [:index, :show]
  end

  resources :lessons, only: [] do
    resources :answers, only: [:index, :create]
  end

  resource :profile, only: [:edit, :update]

  namespace :api do
  end

  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end

  namespace :admin do
    root to: 'main#index'

    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show
    resources :answers, only: [:index, :destroy]

    resources :user_lessons, only: :update do
      resources :answers, only: [:new, :create, :edit, :update]
    end

    resources :courses, except: :show do
      resources :lessons, except: :show
      resources :flows, except: :show
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end

      resources :lessons, only: [] do
        resources :tinymce_images, only: :create, owner: 'lesson'
      end

      resources :user_lessons, only: [] do
        resources :answers, only: :create
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authority::Abilities

  attr_accessor :complete

  belongs_to :user_lesson
  belongs_to :owner, polymorphic: true

  has_many :answer_images, dependent: :destroy

  validate :content_presence

  after_create_commit :change_user_lesson_state

  mount_uploader :audio, AnswerAudioUploader

  accepts_nested_attributes_for :answer_images, reject_if: :all_blank, allow_destroy: true

  def by_teacher?
    owner_type == 'Teacher'
  end

  def by_user?
    owner_type == 'User'
  end

  private

  def content_presence
    if text.blank? && (audio.blank? && errors[:audio].blank?) && no_images?
      errors.add :base, 'Ответ не может быть пустым'
    end
  end

  def no_images?
    answer_images.empty?
  end

  def convert_audio
    Audio::Ogg2mp3.new(self).convert
  end

  def change_user_lesson_state
    if by_teacher?
      if complete
        user_lesson.complete
      else
        user_lesson.give_teacher_answer
      end
    else
      user_lesson.give_answer
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :set_user_lesson, only: [:new, :create, :edit, :update]

  before_action :set_breadcrumbs, only: [:new, :index]
  before_action :set_user_lesson_answers, only: :new

  after_action :mark_answers_as_viewed, only: :new

  def index
    @course = Course.first

    @q = Answer.ransack(search_params)
    @answers = @q.result.order(id: :desc).page(params[:page])
  end

  def new
    @answer = @user_lesson.answers.build
  end

  def create
    @answer = @user_lesson.answers.build(answer_params)
    @answer.owner = @user_lesson.lesson.course.teacher

    if @answer.save
      redirect_to admin_answers_path, notice: 'Ответ успешно сохранен'
    else
      set_breadcrumbs
      set_user_lesson_answers

      flash.now[:alert] =  "Не удалось сохранить ответ. #{@answer.errors.full_messages.join('. ')}."
      render :new
    end
  end

  def edit
    add_breadcrumb 'Редактирование', '#'
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:new, :admin, @user_lesson, @answer], notice: 'Ответ успешно сохранен'
    else
      set_breadcrumbs
      add_breadcrumb 'Редактирование', '#'

      flash.now[:alert] =  "Не удалось сохранить ответ. #{@answer.errors.full_messages.join('. ')}."
      render :edit
    end
  end

  def destroy
    if @answer.destroy
      redirect_to [:new, :admin, @answer.user_lesson, :answer], notice: 'Ответ успешно удален'
    else
      redirect_to [:new, :admin, @answer.user_lesson, :answer], alert: 'Не удалось удалить Ответ'
    end
  end

  private

  def set_user_lesson
    @user_lesson ||= UserLesson.find(params[:user_lesson_id])
  end

  def set_breadcrumbs
    add_breadcrumb "Проверка", [:admin, :answers]

    if @user_lesson
      add_breadcrumb @user_lesson.lesson.course.name,'#'
      add_breadcrumb @user_lesson.lesson.name, '#'
      add_breadcrumb @user_lesson.user.decorate.full_name, '#'
    end
  end

  def set_user_lesson_answers
    @answers = @user_lesson.answers.order(id: :desc)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_active_main_menu_item
    @main_menu[:answers][:active] = true
  end

  def mark_answers_as_viewed
    @answers.map{ |t| t.update(viewed: true) }
  end

  def answer_params
    params.require(:answer).permit(:text, :audio, :complete, answer_images_attributes: [:file, :file_cache, :_destroy])
  end

  def search_params
    return params[:q] if params[:q]

    { viewed_eq: false,
      owner_type_eq: 'User' }
  end
end

app/controllers/admin/api/answers_controller.rb
class Admin::Api::AnswersController < Admin::Api::BaseController
  before_action :set_user_lesson, only: :create

  def create
    @answer = @user_lesson.answers.build(answer_params)
    @answer.owner = @user_lesson.lesson.course.teacher

    if @answer.save
      head :no_content
    else
      render json: @answer.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  private

  def set_user_lesson
    @user_lesson ||= UserLesson.find(params[:user_lesson_id])
  end

  def answer_params
    params.require(:answer).permit(:text, :audio, :complete, answer_images_attributes: [:file, :file_cache, :_destroy])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationBaseController
  before_action :authenticate_user!
  before_action :set_lesson_and_course
  before_action :set_user_lesson

  layout false

  def index
    authorize_action_for @lesson

    if @lesson.without_homework?
      redirect_to [@course, @lesson], alert: 'У занятия нет домашнего задания'
      return
    end

    @answer = Answer.new()
    @answer.answer_images.build
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.owner = current_user
    @answer.user_lesson = @user_lesson

    authorize_action_for @answer

    if @answer.save
      flash[:notice] = 'Ответ успешно сохранен'
      head :no_content
    else
      @answer.answer_images.build if @answer.answer_images.empty?
      render :index, status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:text, answer_images_attributes: [:file, :file_cache, :_destroy])
  end

  def set_lesson_and_course
    @lesson = Lesson.find(params[:lesson_id])
    @course = @lesson.course
  end

  def set_user_lesson
    @user_lesson = current_user.user_lessons.find_by(lesson: @lesson)
  end
end

app/views/admin/answers/_answer.html.slim
.panel class="panel-#{answer.viewed? ? 'default' : 'warning'}"
  .panel-heading
    - if answer.user_lesson.lesson.stop_lesson?
      span.text-danger.glyphicon.glyphicon-exclamation-sign.margin-right-10

    b= answer.user_lesson.lesson.name

    span.label.margin-left-10 class="label-#{answer.user_lesson.decorate.state_class}"
      = t("activerecord.state_machines.user_lesson.states.#{answer.user_lesson.state}")

    .pull-right
      = l(answer.created_at, format: :short)

  .panel-body
    .row
      .col-md-2
        .media
          .media-left
            = image_tag answer.owner.avatar.small
          .media-body
            = answer.owner.decorate.full_name

        .btn-group-vertical.padding-top-20 role="group"
          - if action_name == 'index'
            = link_to 'Ответить', [:new, :admin, answer.user_lesson, :answer], class: 'btn btn-primary btn-sm'
          - else
            - if answer.by_teacher?
              = link_to 'Редактировать', [:edit, :admin, answer.user_lesson, answer], class: 'btn btn-info btn-sm'
            = link_to 'Удалить', [:admin, answer], class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Действительно хотите удалить?' }

      .col-md-10
        - if answer.audio.present?
          audio.margin-bottom-10.width-100-percentage controls=true controlsList="nodownload" src=answer.audio.url

        p= answer.text if answer.text.present?

        - answer.answer_images.each do |answer_image|
          .col-lg-3.col-md-4.col-sm-4.padding-bottom-10
            = link_to image_path(answer_image.file.big), data: { lightbox: "answer_image_#{answer.id}" } do
              = image_tag answer_image.file.small

app/views/admin/answers/_answer_image_fields.html.slim
.nested-fields
  = f.input :file, wrapper: :horizontal_file_input
  = f.input :file_cache, as: :hidden

  .col-md-offset-3.padding-bottom-10
    = link_to_remove_association "Удалить", f, class: 'btn btn-danger btn-xs'

app/views/admin/answers/_form.html.slim
= simple_form_for [:admin, @user_lesson, @answer], wrapper: :horizontal_form, html: { class: 'form-horizontal sound-recorder', data: { 'api-url' => admin_api_user_lesson_answers_path(@user_lesson, @answer) } }  do |f|

  .col-md-11.col-md-offset-3.button_box.margin-top-10
    = link_to '#', class: 'record btn btn-default btn-sm' do
      span.text-danger.glyphicon.glyphicon-record.margin-right-3
      = 'Записать Ответ'

    = link_to '#', class: 'stop btn btn-default btn-sm hidden' do
      = image_tag('spinners/recording.gif')
      = 'Остановить Запись'

    .sound-clips

  = f.input :text

  #answer_images
    = f.simple_fields_for :answer_images do |form|
      = render 'answer_image_fields', f: form

    .col-md-offset-3.padding-bottom-10
      = link_to_add_association 'Добавить картинку', f, :answer_images, class: 'btn btn-primary btn-xs'

  - unless @user_lesson.completed?
    = f.input :complete, as: :boolean, label: 'Принять после сохранения', wrapper: :horizontal_radio_and_checkboxes

  .col-md-11.col-md-offset-3.errors_block

  .row
    .col-md-11.col-md-offset-3.button_box.margin-top-10
      = f.button :submit,  'Сохранить', class: 'btn btn-primary'

      - unless @user_lesson.completed?
        = link_to 'Принять', [:admin, @user_lesson, user_lesson: { state_event: :complete }], method: :patch, class: 'btn btn-success', data: { confirm: 'Действительно хотите принять без сохранения?' }
      - if @user_lesson.completed?
        = link_to 'Вернуть на Доделку', [:admin, @user_lesson, user_lesson: { state_event: :reject }], method: :patch, class: 'btn btn-warning', data: { confirm: 'Действительно хотите Вернуть на доделку без сохранения?' }
      = link_to 'Отменить', admin_answers_path, class: 'btn btn-default'

app/views/admin/answers/_search_form.html.slim
.row
  = search_form_for [:admin, @q], builder: SimpleForm::FormBuilder, wrapper: :horizontal_form, html: { class: 'form-horizontal' } do |f|
    .col-md-6
      = f.input :viewed_eq, collection: [['Да', true], ['Нет', false]], required: false, label: 'Просмотрен'
      = f.input :owner_type_eq, collection: [['Пользователь', 'User'], ['Преподаватель', 'Teacher']], required: false, label: 'Принадлежит'
      = f.input :owner_of_User_type_id_eq, collection: @course.users.map{ |t| [t.decorate.full_name, t.id] }, required: false, label: 'Пользователь'

    .col-md-6
      = f.input :user_lesson_lesson_id_eq, collection: @course.lessons.order(:position).map{ |t| [t.name, t.id] }, required: false, label: 'Занятие'
      = f.input :user_lesson_lesson_stop_lesson_eq, collection: [['Да', true], ['Нет', false]], required: false, label: 'Стоп занятие'
      = f.input :user_lesson_state_in, collection: UserLesson.state_machine.states.map{ |state| [t("activerecord.state_machines.user_lesson.states.#{state.name}"), state.name] }, input_html: { multiple: true }, required: false, label: 'Статус'


    = f.button :submit, 'Искать', class: 'btn btn-primary pull-right margin-right-20 margin-bottom-10'

app/views/admin/answers/edit.html.slim
h3 Редактирование ответа

= render 'form'

app/views/admin/answers/index.html.slim
h3 Ответы

= link_to "#search_form", class: "btn btn-default margin-bottom-10", role:  "button", data: { toggle: "collapse" }, aria: { expanded: false, controls: "search_form" } do
  span.glyphicon.glyphicon-search

.collapse#search_form
  = render 'search_form'

= render @answers

= paginate @answers, theme: 'twitter-bootstrap-3'

app/views/admin/answers/new.html.slim
h3 Ответы

= render 'form'

.margin-top-20
  = render @answers