config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get 'contact', to: 'static_pages#contact'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' },
                     path_names: { sign_in: 'login',
                                   sign_out: 'logout',
                                   password: 'secret',
                                   sign_up: 'registration' }

  resources :courses, only: :show do
    resources :lessons, only: [:index, :show]
  end

  resources :lessons, only: [] do
    resources :answers, only: [:index, :create]
  end

  resource :profile, only: [:edit, :update]

  namespace :api do
  end

  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end

  namespace :admin do
    root to: 'main#index'

    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show
    resources :answers, only: [:index, :destroy]

    resources :user_lessons, only: :update do
      resources :answers, only: [:new, :create, :edit, :update]
    end

    resources :courses, except: :show do
      resources :lessons, except: :show
      resources :flows, except: :show
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end

      resources :lessons, only: [] do
        resources :tinymce_images, only: :create, owner: 'lesson'
      end

      resources :user_lessons, only: [] do
        resources :answers, only: :create
      end
    end
  end
end

app/views/admin/admins/_admin.html.slim
tr
  td
    .btn-group-vertical role="group"
      = link_to [:edit, :admin, admin], class: 'btn btn-primary btn-sm' do
        span.glyphicon.glyphicon-pencil aria-hidden="true"
      = link_to [:admin, admin], class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Действительно хотите удалить?' } do
        span.glyphicon.glyphicon-trash aria-hidden="true"
  td= admin.email
  td= admin.first_name
  td= admin.last_name

app/views/admin/admins/_form.html.slim
= simple_form_for [:admin, @admin], wrapper: :horizontal_form, html: { class: 'form-horizontal' } do |f|
  = f.input :email
  = f.input :first_name
  = f.input :last_name
  = f.input :password
  = f.input :password_confirmation

  .row
    .col-md-11.col-md-offset-3.button_box
      = f.button :submit,  'Сохранить', class: 'btn btn-primary'
      = link_to 'Отменить', admin_admins_path, class: 'btn btn-default'
      = link_to 'Удалить', [:admin, @admin], class: 'btn btn-danger', method: :delete, data: { confirm: 'Действительно хотите удалить?' } if @admin.persisted?

app/views/admin/admins/edit.html.slim
h3 Редактирование Админа

= render 'form'

app/views/admin/admins/index.html.slim
h3 Админы

= link_to 'Добавить админа', new_admin_admin_path, class: 'btn btn-success pull-right'

table.table.table-striped
  thead
    tr
      th
      th Email
      th Имя
      th Фамилия
  tbody
    = render @admins

= paginate @admins, theme: 'twitter-bootstrap-3'

app/views/admin/admins/new.html.slim
h3 Новый Админ
hr

= render 'form'